#!/usr/bin/env python3
#
#    Copyright (C) 2021 @lyazj
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

import os
import sys
import multiprocessing

os.chdir(os.path.dirname(__file__))

jobs = multiprocessing.cpu_count()
linkage = str()
bits = str()

sys.argv = sys.argv[1:]

if len(sys.argv) > 0:
  if sys.argv[0] == '32':
    linkage = " -e 'linkage=WIN'"
    bits = " -e 'bits=32'"
    sys.argv = sys.argv[1:]
  elif sys.argv[0] == '64':
    linkage = " -e 'linkage=WIN'"
    bits = " -e 'bits=64'"
    sys.argv = sys.argv[1:]

os.system(' '.join([f"make -j {jobs}{linkage}{bits}"] + sys.argv))
